<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Test\Dao\Bean;
 
/**
 * The PatcheBean class maps the 'patches' table in database.
 * @dbTable patches
 *
 */
class PatcheBean extends PatcheBaseBean 
{

}