<?php
namespace Test\Dao\Bean;

use Mouf\Database\TDBM\TDBMObject;

/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 * If you need to perform changes, edit the ProjectBean class instead!
 */

/**
 * The ProjectBaseBean class maps the 'project' table in database.
 * @dbTable project
 */
class ProjectBaseBean extends TDBMObject 
{
	/**
	 * The getter for the "id" column.
	 *
	 * @dbType int
	 * @dbColumn id
	 * @return string
	 */
	public function getId(){
		return $this->__get('id');
	}
	
	/**
	 * The setter for the "id" column.
	 *
	 * @dbColumn id
	 * @param string $id
	 */
	public function setId($id) {
		$this->__set('id', $id);
	}
	
	/**
	 * The getter for the "user_id" column.
	 *
	 * @dbType int
	 * @dbColumn user_id
	 * @return string
	 */
	public function getUserId(){
		return $this->__get('user_id');
	}
	
	/**
	 * The setter for the "user_id" column.
	 *
	 * @dbColumn user_id
	 * @param string $user_id
	 */
	public function setUserId($user_id) {
		$this->__set('user_id', $user_id);
	}
	
	/**
	 * The getter for the "label" column.
	 *
	 * @dbType string
	 * @dbColumn label
	 * @return string
	 */
	public function getLabel(){
		return $this->__get('label');
	}
	
	/**
	 * The setter for the "label" column.
	 *
	 * @dbColumn label
	 * @param string $label
	 */
	public function setLabel($label) {
		$this->__set('label', $label);
	}
	
	/**
	 * Returns the UserBean object bound to this object via the user_id column.
	 * 
	 * @return UserBean
	 */
	public function getUserByUserId() {
		if ($this->user_id == null) {
			return null;
		}
		return $this->tdbmService->getObject("user", $this->user_id, "Test\\Dao\\Bean\\UserBean", true);
	}
	
	/**
	 * The setter for the UserBean object bound to this object via the user_id column.
	 *
	 * @param UserBean $object
	 */
	public function setUserByUserId(UserBean $object = null) {
		$this->__set('user_id', ($object == null)?null:$object->__get('id'));
	}
	
	/**
	 * Returns the UserBean object bound to this object via the user_id column.
	 * This is an alias for the getUserByUserId method.  
	 *
	 * @return UserBean
	 */
	public function getUser() {
		if ($this->user_id == null) {
			return null;
		}
		return $this->tdbmService->getObject("user", $this->user_id, "Test\\Dao\\Bean\\UserBean");
	}
	
	/**
	 * The setter for the "user_id" column.
	 * This is an alias for the setUserByUserId method.
	 *
	 * @param UserBean $object
	 */
	public function setUser(UserBean $object = null) {
		$this->__set('user_id', ($object == null)?null:$object->__get('id'));
	}
	
}
?>