<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Test\Dao\Bean;
 
/**
 * The ProjectTypeBean class maps the 'project_type' table in database.
 * @dbTable project_type
 *
 */
class ProjectTypeBean extends ProjectTypeBaseBean 
{

}