<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Test\Dao\Bean;
 
/**
 * The ProjectBean class maps the 'project' table in database.
 * @dbTable project
 *
 */
class ProjectBean extends ProjectBaseBean 
{

}