<?php
namespace Test\Dao\Bean;

use Mouf\Database\TDBM\TDBMObject;

/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 * If you need to perform changes, edit the RoleBean class instead!
 */

/**
 * The RoleBaseBean class maps the 'role' table in database.
 * @dbTable role
 */
class RoleBaseBean extends TDBMObject 
{
	/**
	 * The getter for the "id" column.
	 *
	 * @dbType int
	 * @dbColumn id
	 * @return string
	 */
	public function getId(){
		return $this->__get('id');
	}
	
	/**
	 * The setter for the "id" column.
	 *
	 * @dbColumn id
	 * @param string $id
	 */
	public function setId($id) {
		$this->__set('id', $id);
	}
	
	/**
	 * The getter for the "label" column.
	 *
	 * @dbType string
	 * @dbColumn label
	 * @return string
	 */
	public function getLabel(){
		return $this->__get('label');
	}
	
	/**
	 * The setter for the "label" column.
	 *
	 * @dbColumn label
	 * @param string $label
	 */
	public function setLabel($label) {
		$this->__set('label', $label);
	}
	
}
?>