<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Test\Dao\Bean;
 
/**
 * The RoleBean class maps the 'role' table in database.
 * @dbTable role
 *
 */
class RoleBean extends RoleBaseBean 
{

}