<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Test\Dao\Bean;
 
/**
 * The SkillBean class maps the 'skill' table in database.
 * @dbTable skill
 *
 */
class SkillBean extends SkillBaseBean 
{

}