<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Test\Dao\Bean;
 
/**
 * The UserSkillBean class maps the 'user_skill' table in database.
 * @dbTable user_skill
 *
 */
class UserSkillBean extends UserSkillBaseBean 
{

}