<?php
namespace Test\Dao\Bean;

use Mouf\Database\TDBM\TDBMObject;

/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 * If you need to perform changes, edit the UserSkillBean class instead!
 */

/**
 * The UserSkillBaseBean class maps the 'user_skill' table in database.
 * @dbTable user_skill
 */
class UserSkillBaseBean extends TDBMObject 
{
	/**
	 * The getter for the "id" column.
	 *
	 * @dbType int
	 * @dbColumn id
	 * @return string
	 */
	public function getId(){
		return $this->__get('id');
	}
	
	/**
	 * The setter for the "id" column.
	 *
	 * @dbColumn id
	 * @param string $id
	 */
	public function setId($id) {
		$this->__set('id', $id);
	}
	
	/**
	 * The getter for the "user_id" column.
	 *
	 * @dbType int
	 * @dbColumn user_id
	 * @return string
	 */
	public function getUserId(){
		return $this->__get('user_id');
	}
	
	/**
	 * The setter for the "user_id" column.
	 *
	 * @dbColumn user_id
	 * @param string $user_id
	 */
	public function setUserId($user_id) {
		$this->__set('user_id', $user_id);
	}
	
	/**
	 * The getter for the "skill_id" column.
	 *
	 * @dbType int
	 * @dbColumn skill_id
	 * @return string
	 */
	public function getSkillId(){
		return $this->__get('skill_id');
	}
	
	/**
	 * The setter for the "skill_id" column.
	 *
	 * @dbColumn skill_id
	 * @param string $skill_id
	 */
	public function setSkillId($skill_id) {
		$this->__set('skill_id', $skill_id);
	}
	
	/**
	 * Returns the SkillBean object bound to this object via the skill_id column.
	 * 
	 * @return SkillBean
	 */
	public function getSkillBySkillId() {
		if ($this->skill_id == null) {
			return null;
		}
		return $this->tdbmService->getObject("skill", $this->skill_id, "Test\\Dao\\Bean\\SkillBean", true);
	}
	
	/**
	 * The setter for the SkillBean object bound to this object via the skill_id column.
	 *
	 * @param SkillBean $object
	 */
	public function setSkillBySkillId(SkillBean $object = null) {
		$this->__set('skill_id', ($object == null)?null:$object->__get('id'));
	}
	
	/**
	 * Returns the UserBean object bound to this object via the user_id column.
	 * 
	 * @return UserBean
	 */
	public function getUserByUserId() {
		if ($this->user_id == null) {
			return null;
		}
		return $this->tdbmService->getObject("user", $this->user_id, "Test\\Dao\\Bean\\UserBean", true);
	}
	
	/**
	 * The setter for the UserBean object bound to this object via the user_id column.
	 *
	 * @param UserBean $object
	 */
	public function setUserByUserId(UserBean $object = null) {
		$this->__set('user_id', ($object == null)?null:$object->__get('id'));
	}
	
	/**
	 * Returns the SkillBean object bound to this object via the skill_id column.
	 * This is an alias for the getSkillBySkillId method.  
	 *
	 * @return SkillBean
	 */
	public function getSkill() {
		if ($this->skill_id == null) {
			return null;
		}
		return $this->tdbmService->getObject("skill", $this->skill_id, "Test\\Dao\\Bean\\SkillBean");
	}
	
	/**
	 * The setter for the "skill_id" column.
	 * This is an alias for the setSkillBySkillId method.
	 *
	 * @param SkillBean $object
	 */
	public function setSkill(SkillBean $object = null) {
		$this->__set('skill_id', ($object == null)?null:$object->__get('id'));
	}
	
	/**
	 * Returns the UserBean object bound to this object via the user_id column.
	 * This is an alias for the getUserByUserId method.  
	 *
	 * @return UserBean
	 */
	public function getUser() {
		if ($this->user_id == null) {
			return null;
		}
		return $this->tdbmService->getObject("user", $this->user_id, "Test\\Dao\\Bean\\UserBean");
	}
	
	/**
	 * The setter for the "user_id" column.
	 * This is an alias for the setUserByUserId method.
	 *
	 * @param UserBean $object
	 */
	public function setUser(UserBean $object = null) {
		$this->__set('user_id', ($object == null)?null:$object->__get('id'));
	}
	
}
?>