<?php
namespace Test\Dao\Bean;

use Mouf\Database\TDBM\TDBMObject;

/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 * If you need to perform changes, edit the UserBean class instead!
 */

/**
 * The UserBaseBean class maps the 'user' table in database.
 * @dbTable user
 */
class UserBaseBean extends TDBMObject 
{
	/**
	 * The getter for the "id" column.
	 *
	 * @dbType int
	 * @dbColumn id
	 * @return string
	 */
	public function getId(){
		return $this->__get('id');
	}
	
	/**
	 * The setter for the "id" column.
	 *
	 * @dbColumn id
	 * @param string $id
	 */
	public function setId($id) {
		$this->__set('id', $id);
	}
	
	/**
	 * The getter for the "role_id" column.
	 *
	 * @dbType int
	 * @dbColumn role_id
	 * @return string
	 */
	public function getRoleId(){
		return $this->__get('role_id');
	}
	
	/**
	 * The setter for the "role_id" column.
	 *
	 * @dbColumn role_id
	 * @param string $role_id
	 */
	public function setRoleId($role_id) {
		$this->__set('role_id', $role_id);
	}
	
	/**
	 * The getter for the "name" column.
	 *
	 * @dbType string
	 * @dbColumn name
	 * @return string
	 */
	public function getName(){
		return $this->__get('name');
	}
	
	/**
	 * The setter for the "name" column.
	 *
	 * @dbColumn name
	 * @param string $name
	 */
	public function setName($name) {
		$this->__set('name', $name);
	}
	
	/**
	 * The getter for the "email" column.
	 *
	 * @dbType string
	 * @dbColumn email
	 * @return string
	 */
	public function getEmail(){
		return $this->__get('email');
	}
	
	/**
	 * The setter for the "email" column.
	 *
	 * @dbColumn email
	 * @param string $email
	 */
	public function setEmail($email) {
		$this->__set('email', $email);
	}
	
	/**
	 * The getter for the "birth_date" column.
	 * It is returned as a PHP timestamp.
	 *
	 * @dbType date
	 * @dbColumn birth_date
	 * @return timestamp
	 */
	public function getBirthDate() {
		$date = $this->__get('birth_date');
		if($date === null)
			return null;
		else
			return strtotime($date);
	}
	
	/**
	 * The setter for the "birth_date" column.
	 * It must be provided as a PHP timestamp.
	 *
	 * @dbColumn birth_date
	 * @param timestamp $birth_date
	 */
	public function setBirthDate($birth_date) {
		if($birth_date === null) {
			$this->__set('birth_date', null);
		} else {
			$this->__set('birth_date', date("Y-m-d H:i:s", $birth_date));
						
		}
	}
	
	/**
	 * The getter for the "story" column.
	 *
	 * @dbType string
	 * @dbColumn story
	 * @return string
	 */
	public function getStory(){
		return $this->__get('story');
	}
	
	/**
	 * The setter for the "story" column.
	 *
	 * @dbColumn story
	 * @param string $story
	 */
	public function setStory($story) {
		$this->__set('story', $story);
	}
	
	/**
	 * Returns the RoleBean object bound to this object via the role_id column.
	 * 
	 * @return RoleBean
	 */
	public function getRoleByRoleId() {
		if ($this->role_id == null) {
			return null;
		}
		return $this->tdbmService->getObject("role", $this->role_id, "Test\\Dao\\Bean\\RoleBean", true);
	}
	
	/**
	 * The setter for the RoleBean object bound to this object via the role_id column.
	 *
	 * @param RoleBean $object
	 */
	public function setRoleByRoleId(RoleBean $object = null) {
		$this->__set('role_id', ($object == null)?null:$object->__get('id'));
	}
	
	/**
	 * Returns the RoleBean object bound to this object via the role_id column.
	 * This is an alias for the getRoleByRoleId method.  
	 *
	 * @return RoleBean
	 */
	public function getRole() {
		if ($this->role_id == null) {
			return null;
		}
		return $this->tdbmService->getObject("role", $this->role_id, "Test\\Dao\\Bean\\RoleBean");
	}
	
	/**
	 * The setter for the "role_id" column.
	 * This is an alias for the setRoleByRoleId method.
	 *
	 * @param RoleBean $object
	 */
	public function setRole(RoleBean $object = null) {
		$this->__set('role_id', ($object == null)?null:$object->__get('id'));
	}
	
}
?>