<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Test\Dao\Bean;
 
/**
 * The UserBean class maps the 'user' table in database.
 * @dbTable user
 *
 */
class UserBean extends UserBaseBean 
{

}