<?php
/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 */
namespace Test\Dao;
		
/**
 * The DaoFactory provides an easy access to all DAOs generated by TDBM.
 *
 * @Component
 */
class DaoFactory 
{
	/**
	 * @var PatcheDao
	 */
	private $patcheDao;

	/**
	 * Returns an instance of the PatcheDao class.
	 * 
	 * @return PatcheDao
	 */
	public function getPatcheDao() {
		return $this->patcheDao;
	}
	
	/**
	 * Sets the instance of the PatcheDao class that will be returned by the factory getter.
	 * 
	 * @Property
	 * @Compulsory
	 * @param PatcheDao $patcheDao
	 */
	public function setPatcheDao(PatcheDao $patcheDao) {
		$this->patcheDao = $patcheDao;
	}
	
	/**
	 * @var ProjectDao
	 */
	private $projectDao;

	/**
	 * Returns an instance of the ProjectDao class.
	 * 
	 * @return ProjectDao
	 */
	public function getProjectDao() {
		return $this->projectDao;
	}
	
	/**
	 * Sets the instance of the ProjectDao class that will be returned by the factory getter.
	 * 
	 * @Property
	 * @Compulsory
	 * @param ProjectDao $projectDao
	 */
	public function setProjectDao(ProjectDao $projectDao) {
		$this->projectDao = $projectDao;
	}
	
	/**
	 * @var RoleDao
	 */
	private $roleDao;

	/**
	 * Returns an instance of the RoleDao class.
	 * 
	 * @return RoleDao
	 */
	public function getRoleDao() {
		return $this->roleDao;
	}
	
	/**
	 * Sets the instance of the RoleDao class that will be returned by the factory getter.
	 * 
	 * @Property
	 * @Compulsory
	 * @param RoleDao $roleDao
	 */
	public function setRoleDao(RoleDao $roleDao) {
		$this->roleDao = $roleDao;
	}
	
	/**
	 * @var SkillDao
	 */
	private $skillDao;

	/**
	 * Returns an instance of the SkillDao class.
	 * 
	 * @return SkillDao
	 */
	public function getSkillDao() {
		return $this->skillDao;
	}
	
	/**
	 * Sets the instance of the SkillDao class that will be returned by the factory getter.
	 * 
	 * @Property
	 * @Compulsory
	 * @param SkillDao $skillDao
	 */
	public function setSkillDao(SkillDao $skillDao) {
		$this->skillDao = $skillDao;
	}
	
	/**
	 * @var UserDao
	 */
	private $userDao;

	/**
	 * Returns an instance of the UserDao class.
	 * 
	 * @return UserDao
	 */
	public function getUserDao() {
		return $this->userDao;
	}
	
	/**
	 * Sets the instance of the UserDao class that will be returned by the factory getter.
	 * 
	 * @Property
	 * @Compulsory
	 * @param UserDao $userDao
	 */
	public function setUserDao(UserDao $userDao) {
		$this->userDao = $userDao;
	}
	
	/**
	 * @var UserSkillDao
	 */
	private $userSkillDao;

	/**
	 * Returns an instance of the UserSkillDao class.
	 * 
	 * @return UserSkillDao
	 */
	public function getUserSkillDao() {
		return $this->userSkillDao;
	}
	
	/**
	 * Sets the instance of the UserSkillDao class that will be returned by the factory getter.
	 * 
	 * @Property
	 * @Compulsory
	 * @param UserSkillDao $userSkillDao
	 */
	public function setUserSkillDao(UserSkillDao $userSkillDao) {
		$this->userSkillDao = $userSkillDao;
	}
	

}
?>