<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace Test\Dao;

/**
 * The PatcheDao class will maintain the persistance of Test\Dao\Bean\PatcheBean class into the patches table.
 *
 * @Component
 * @dbTable patches
 */
class PatcheDao extends PatcheDaoBase
{

}