<?php
/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 * If you need to perform changes, edit the PatcheDao class instead!
 */
namespace Test\Dao;

use Mouf\Database\DAOInterface;
use Mouf\Database\TDBM\TDBMService; 
use Mouf\Database\TDBM\Filters\OrderByColumn;

/**
 * The PatcheDaoBase class will maintain the persistance of Test\Dao\Bean\PatcheBean class into the patches table.
 * 
 */
class PatcheDaoBase implements DAOInterface
{

	/**
	 * @var TDBMService
	 */
	protected $tdbmService;
	
	/**
	 * The default Sort column
	 * @var string
	 */
	private $defaultSort = null;
	
	/**
	 * The default Sort direction
	 * @var string
	 */
	private $defaultDirection = 'asc';
	
	/**
	 * Sets the TDBM service used by this DAO.
	 *
	 * @Property
	 * @Compulsory
	 * @param TDBMService $tdbmService
	 */
	public function setTdbmService(TDBMService $tdbmService) {
		$this->tdbmService = $tdbmService;
	}

	/**
	 * Return a new instance of Test\Dao\Bean\PatcheBean object, that will be persisted in database.
	 *
	 * @return Test\Dao\Bean\PatcheBean
	 */
	public function create() {
		return $this->tdbmService->getNewObject('patches', true, 'Test\Dao\Bean\PatcheBean');
	}
	
	/**
	 * Persist the Test\Dao\Bean\PatcheBean instance
	 *
	 */
	public function save($obj) {
		$obj->save();
	}

	/**
	 * Get all Patche records. 
	 *
	 * @return array<Test\Dao\Bean\PatcheBean>
	 */
	public function getList() {
		if ($this->defaultSort){
			$orderBy = new OrderByColumn('patches', $this->defaultSort, $this->defaultDirection);
		}else{
			$orderBy = null;
		}
		return $this->tdbmService->getObjects('patches',  null, $orderBy, null, null, 'Test\Dao\Bean\PatcheBean');
	}
	
	/**
	 * Get Test\Dao\Bean\PatcheBean specified by its ID (its primary key)
	 * If the primary key does not exist, an exception is thrown.
	 *
	 * @param string $id
	 * @param boolean $lazyLoading If set to true, the object will not be loaded right away. Instead, it will be loaded when you first try to access a method of the object.
	 * @return Test\Dao\Bean\PatcheBean
	 * @throws TDBMException
	 */
	public function getById($id, $lazyLoading = false) {
		return $this->tdbmService->getObject('patches', $id, 'Test\Dao\Bean\PatcheBean', $lazyLoading);
	}
	
	/**
	 * Deletes the Test\Dao\Bean\PatcheBean passed in parameter.
	 *
	 * @param Test\Dao\Bean\PatcheBean $obj
	 */
	public function delete($obj) {
		$this->tdbmService->deleteObject($obj);
	}
	
	/**
	 * Get a list of Test\Dao\Bean\PatcheBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @param mixed $orderbyBag The order bag (see TDBMService::getObjects for complete description)
	 * @param integer $from The offset
	 * @param integer $limit The maximum number of rows returned
	 * @return array<Test\Dao\Bean\PatcheBean>
	 */
	protected function getListByFilter($filterBag=null, $orderbyBag=null, $from=null, $limit=null) {
		if ($this->defaultSort && $orderbyBag == null){
			$orderbyBag = new OrderByColumn('patches', $this->defaultSort, $this->defaultDirection);
		}
		return $this->tdbmService->getObjects('patches', $filterBag, $orderbyBag, $from, $limit, 'Test\Dao\Bean\PatcheBean');
	}

	/**
	 * Get a single Test\Dao\Bean\PatcheBean specified by its filters.
	 *
	 * @param mixed $filterBag The filter bag (see TDBMService::getObjects for complete description)
	 * @return Test\Dao\Bean\PatcheBean
	 */
	protected function getByFilter($filterBag=null) {
		return $this->tdbmService->getObject('patches', $filterBag, 'Test\Dao\Bean\PatcheBean');
	}
	
	/**
	 * Sets the default column for default sorting
	 *
	 */
	public function setDefaultSort($defaultSort){
		$this->defaultSort = $defaultSort;
	}
	
}
?>