<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace Test\Dao;

/**
 * The ProjectTypeDao class will maintain the persistance of Test\Dao\Bean\ProjectTypeBean class into the project_type table.
 *
 * @Component
 * @dbTable project_type
 */
class ProjectTypeDao extends ProjectTypeDaoBase
{

}