<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace Test\Dao;

use Test\Dao\Bean\UserBean;

/**
 * The ProjectDao class will maintain the persistance of Test\Dao\Bean\ProjectBean class into the project table.
 *
 * @Component
 * @dbTable project
 */
class ProjectDao extends ProjectDaoBase
{
	
	/**
	 * Returns the list of projects owned by a given user
	 * @param UserBean $user
	 * @return Test\Dao\Bean\ProjectBean[]
	 */
	public function getByUserBean(UserBean $user){
		return $this->getListByFilter($user);
	}

}