<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace Test\Dao;

/**
 * The RoleDao class will maintain the persistance of Test\Dao\Bean\RoleBean class into the role table.
 *
 * @Component
 * @dbTable role
 */
class RoleDao extends RoleDaoBase
{

}