<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace Test\Dao;

/**
 * The SkillDao class will maintain the persistance of Test\Dao\Bean\SkillBean class into the skill table.
 *
 * @Component
 * @dbTable skill
 */
class SkillDao extends SkillDaoBase
{

}