<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */
namespace Test\Dao;

/**
 * The UserDao class will maintain the persistance of Test\Dao\Bean\UserBean class into the user table.
 *
 * @Component
 * @dbTable user
 */
class UserDao extends UserDaoBase
{

}