<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */
use Mouf\MoufManager;
MoufManager::initMoufManager();
$moufManager = MoufManager::getMoufManager();

$moufManager->getConfigManager()->setConstantsDefinitionArray(array (
  'DB_HOST' => 
  array (
    'defaultValue' => 'localhost',
    'type' => 'string',
    'comment' => 'The database host (the IP address or URL of the database server).',
  ),
  'DB_PORT' => 
  array (
    'defaultValue' => '',
    'type' => 'int',
    'comment' => 'The database port (the port of the database server, keep empty to use default port).',
  ),
  'DB_NAME' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The name of your database.',
  ),
  'DB_USERNAME' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The username to access the database.',
  ),
  'DB_PASSWORD' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The password to access the database.',
  ),
  'SECRET' => 
  array (
    'defaultValue' => 'zSkDnJ5CqtIUlOyZcZrO',
    'type' => 'string',
    'comment' => 'A random string. It should be different for any application deployed.',
  ),
  'DEBUG_MODE' => 
  array (
    'defaultValue' => true,
    'type' => 'bool',
    'comment' => 'When the application is in debug mode, stacktraces are outputed directly to the user. Otherwise, they are hidden.',
  ),
));

$moufManager->setAllVariables(array (
  'tdbmDefaultSourceDirectory_tdbmService' => 'src/',
  'tdbmDefaultDaoNamespace_tdbmService' => 'Test\\Dao',
  'tdbmDefaultBeanNamespace_tdbmService' => 'Test\\Dao\\Bean',
  'tdbmDefaultDaoFactoryName_tdbmService' => 'DaoFactory',
  'tdbmDefaultDaoFactoryInstanceName_tdbmService' => 'daoFactory',
  'tdbmDefaultKeepSupport_tdbmService' => 0,
  'tdbmDefaultStoreInUtc_tdbmService' => 0,
  'tdbmDefaultSourceDirectory' => 'src/',
  'tdbmDefaultDaoNamespace' => 'Test\\Dao',
  'tdbmDefaultBeanNamespace' => 'Test\\Dao\\Bean',
  'tdbmDefaultDaoFactoryName' => 'DaoFactory',
  'tdbmDefaultDaoFactoryInstanceName' => 'daoFactory',
  'tdbmDefaultKeepSupport' => 0,
  'tdbmDefaultStoreInUtc' => 0,
  'splashDefaultSourceDirectory' => 'src/',
  'splashDefaultControllersNamespace' => 'Test\\Controllers\\',
  'splashDefaultViewsDirectory' => 'views/',
));

$moufManager->addComponentInstances(array (
  '__anonymous__743966_1390581890217' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\BCEFormInstance',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
    'fieldProperties' => 
    array (
    ),
    'fieldBinds' => 
    array (
      'form' => 'userForm',
    ),
  ),
  'apcCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\ApcCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => 3600,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'fallback' => 'fileCacheService',
    ),
  ),
  'aseRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\FormRenderers\\Bootstrap\\BootstrapFormRenderer',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'skin' => 'javascript.bootstrap',
    ),
  ),
  'bceUtils' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Services\\BCEUtils',
    'external' => false,
    'weak' => false,
  ),
  'block.content' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.footer' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.header' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
    ),
    'fieldBinds' => 
    array (
      'children' => 
      array (
        0 => 'messageWidget',
      ),
    ),
  ),
  'block.left' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.right' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'blockDescriptionRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\FormRenderers\\Bootstrap\\Wrappers\\DescriptionRenderer\\BlockDescriptionRenderer',
    'external' => false,
    'weak' => false,
  ),
  'boldFormatter' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Formatters\\PrefixSuffixFormatter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '<b>',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => '</b>',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'booleanFieldRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Renderers\\BooleanFieldRenderer',
    'external' => false,
    'weak' => false,
  ),
  'bootstrapFormRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\FormRenderers\\Bootstrap\\BootstrapFormRenderer',
    'external' => false,
    'weak' => false,
  ),
  'bootstrapRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.template.bootstrap/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'template',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'bootstrapSubFormItemWrapper' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\FormRenderers\\Bootstrap\\Wrappers\\BootstrapSubFormItemWrapper',
    'external' => false,
    'weak' => false,
  ),
  'bootstrapTemplate' => 
  array (
    'class' => 'Mouf\\Html\\Template\\BootstrapTemplate',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setContent' => 'block.content',
      'setLeft' => 'block.left',
      'setRight' => 'block.right',
      'setHeader' => 'block.header',
      'setFooter' => 'block.footer',
      'setWebLibraryManager' => 'defaultWebLibraryManager',
      'setTemplateRenderer' => 'bootstrapRenderer',
      'setDefaultRenderer' => 'defaultRenderer',
    ),
  ),
  'colorPickerRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Renderers\\ColorPickerRenderer',
    'external' => false,
    'weak' => false,
  ),
  'customRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'custom',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'daoFactory' => 
  array (
    'class' => 'Test\\Dao\\DaoFactory',
    'external' => false,
    'setterBinds' => 
    array (
      'setProjectDao' => 'projectDao',
      'setRoleDao' => 'roleDao',
      'setSkillDao' => 'skillDao',
      'setUserDao' => 'userDao',
      'setUserSkillDao' => 'userSkillDao',
    ),
  ),
  'datePickerRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Renderers\\DatePickerRenderer',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'settings' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'dbConnection' => 
  array (
    'class' => 'Mouf\\Database\\DBConnection\\MySqlConnection',
    'external' => false,
    'fieldProperties' => 
    array (
      'host' => 
      array (
        'value' => 'DB_HOST',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'port' => 
      array (
        'value' => 'DB_PORT',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'user' => 
      array (
        'value' => 'DB_USERNAME',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'password' => 
      array (
        'value' => 'DB_PASSWORD',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'dbname' => 
      array (
        'value' => 'DB_NAME',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'defaultFieldWrapperRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\FormRenderers\\Bootstrap\\Wrappers\\DefaultFieldWrapperRenderer',
    'external' => false,
    'weak' => false,
  ),
  'defaultLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\BrowserLanguageDetection',
    'external' => false,
    'weak' => false,
  ),
  'defaultRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\AutoChainRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'defaultTranslationService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'defaultLanguageDetection',
    ),
  ),
  'defaultWebLibraryManager' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibraryManager',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setWebLibraries' => 
      array (
        0 => 'rootUrlInlineWebLibrary',
        1 => 'jQueryLibrary',
        2 => 'javascript.bootstrap',
        3 => 'messageServiceLibrary',
        4 => 'javascript.ckeditor',
        5 => 'fileUploaderLibrary',
        6 => 'jQueryUiLibrary',
        7 => 'jQueryValidateLibrary',
        8 => 'jQueryHistory',
        9 => 'evolugridLibrary',
      ),
    ),
  ),
  'defaultWebLibraryRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\DefaultWebLibraryRenderer',
    'external' => false,
  ),
  'emailValidator' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Validators\\EmailValidator',
    'external' => false,
    'weak' => false,
  ),
  'errorLogLogger' => 
  array (
    'class' => 'Mouf\\Utils\\Log\\ErrorLogLogger',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'level' => 
      array (
        'value' => 4,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'evolugridLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.widgets.evolugrid/js/evolugrid.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
      'setDependencies' => 
      array (
        0 => 'jQueryLibrary',
      ),
    ),
  ),
  'falseCondition' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\ConditionInterface\\FalseCondition',
    'external' => false,
    'weak' => false,
  ),
  'fileCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\FileCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => 3600,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'fileUploaderLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.fileuploader/fileuploader.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.fileuploader/fileuploader.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'fileUploaderRendererNoonlyOneFile' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Renderers\\FileUploaderRenderer',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'onlyOneFile' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'fileUploaderRendereronlyOneFile' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Renderers\\FileUploaderRenderer',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'onlyOneFile' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'fineCommonTranslationService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'defaultLanguageDetection',
    ),
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'vendor/mouf/utils.i18n.fine/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'hiddenRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Renderers\\HiddenRenderer',
    'external' => false,
    'weak' => false,
  ),
  'httpErrorsController' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'template' => 'bootstrapTemplate',
      'contentBlock' => 'block.content',
    ),
    'fieldProperties' => 
    array (
      'debugMode' => 
      array (
        'value' => 'DEBUG_MODE',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'italicFormatter' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Formatters\\PrefixSuffixFormatter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '<i>',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => '</i>',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'jQueryHistory' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.historyjs/scripts/bundled/html4+html5/jquery.history.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'jQueryLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery/jquery-1.9.1.min.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'jQueryUiLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery-ui/js/jquery-ui-1.10.2.custom.min.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery-ui/css/ui-lightness/jquery-ui-1.10.2.custom.min.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
      'setDependencies' => 
      array (
        0 => 'jQueryLibrary',
      ),
    ),
  ),
  'jQueryValidateLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\I18nWebLibrary\\I18nWebLibrary',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'languageDetection' => 'defaultLanguageDetection',
    ),
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery-validate/jquery.validate.min.js',
          1 => 'vendor/mouf/javascript.jquery.jquery-validate/localization/messages_[lang].js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
      'setDependencies' => 
      array (
        0 => 'jQueryLibrary',
      ),
    ),
  ),
  'javascript.bootstrap' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/twitter/bootstrap/dist/js/bootstrap.min.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'vendor/twitter/bootstrap/dist/css/bootstrap.min.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'javascript.ckeditor' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.utils.ckeditor/ckeditor/ckeditor.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'messageServiceLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.widgets.messageservice/messages.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'messageWidget' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\MessageService\\Widget\\MessageWidget',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'messageProvider' => 'userMessageService',
    ),
  ),
  'multipleSelectFieldRenderer2' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Renderers\\MultipleSelectFieldRenderer',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'mode' => 
      array (
        'value' => 'chbx',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'noCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\NoCache',
    'external' => false,
    'weak' => false,
  ),
  'noWrapFieldWrapperRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\FormRenderers\\NoWrapFieldWrapperRenderer',
    'external' => false,
    'weak' => false,
  ),
  'numericValidatorDecimals' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Validators\\NumericValidator',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'allowDecimals' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/html.widgets.form-elements' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.widgets.form-elements/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/html.widgets.messageservice' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.widgets.messageservice/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'passwordFieldRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Renderers\\PasswordFieldRenderer',
    'external' => false,
    'weak' => false,
  ),
  'projectDao' => 
  array (
    'class' => 'Test\\Dao\\ProjectDao',
    'external' => false,
    'setterBinds' => 
    array (
      'setTdbmService' => 'tdbmService',
    ),
  ),
  'projectForm' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\BCEForm',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'mainDAO' => 'projectDao',
      'scriptManager' => 'scriptManager',
      'idFieldDescriptor' => 'projectFormidDesc',
      'fieldDescriptors' => 
      array (
        0 => 'projectFormlabelDesc',
      ),
      'validationHandler' => 'queryValidateHandler',
      'renderer' => 'aseRenderer',
    ),
    'fieldProperties' => 
    array (
      'isMain' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'action' => 
      array (
        'value' => 'save',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'method' => 
      array (
        'value' => 'POST',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'saveLabel' => 
      array (
        'value' => 'Save changes',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'cancelLabel' => 
      array (
        'value' => 'Cancel',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'attributes' => 
      array (
        'value' => 
        array (
          'name' => 'default_name',
          'id' => 'default_id',
          'acceptCharset' => 'UTF-8',
          'enctype' => 'application/x-www-form-urlencoded',
          'class' => '',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'projectFormidDesc' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Descriptors\\BaseFieldDescriptor',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'fieldName' => 
      array (
        'value' => 'id',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'formatter' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'getter' => 
      array (
        'value' => 'getId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setter' => 
      array (
        'value' => 'setId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Id',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setDescription' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'renderer' => 'hiddenRenderer',
    ),
    'setterBinds' => 
    array (
      'setValidators' => 
      array (
        0 => 'numericValidatorDecimals',
      ),
    ),
  ),
  'projectFormlabelDesc' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Descriptors\\BaseFieldDescriptor',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'fieldName' => 
      array (
        'value' => 'label',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'formatter' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'editCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'viewCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'getter' => 
      array (
        'value' => 'getLabel',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setter' => 
      array (
        'value' => 'setLabel',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'name',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setDescription' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setValidators' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'renderer' => 'textFieldRenderer',
    ),
  ),
  'projectFormuserIdDesc' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Descriptors\\ForeignKeyFieldDescriptor',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'fieldName' => 
      array (
        'value' => 'user_id',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'formatter' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'editCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'viewCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'getter' => 
      array (
        'value' => 'getUserId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setter' => 
      array (
        'value' => 'setUserId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'dataMethod' => 
      array (
        'value' => 'getList',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'linkedIdGetter' => 
      array (
        'value' => 'getId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'linkedLabelGetter' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'User',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setDescription' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'renderer' => 'hiddenRenderer',
      'dao' => 'userDao',
    ),
    'setterBinds' => 
    array (
      'setValidators' => 
      array (
        0 => 'numericValidatorDecimals',
      ),
    ),
  ),
  'psr.errorLogLogger' => 
  array (
    'class' => 'Mouf\\Utils\\Log\\Psr\\ErrorLogLogger',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'warning',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'queryValidateHandler' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\ValidationHandlers\\JQueryValidateHandler',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'jsLib' => 'jQueryValidateLibrary',
    ),
  ),
  'readOnlyCheckBoxFormatter' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Formatters\\ReadOnlyCheckboxFormatter',
    'external' => false,
    'weak' => false,
  ),
  'rendererCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\InMemoryCache',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'chainWith' => 'apcCacheService',
    ),
  ),
  'replaceNullWithHyphen' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Formatters\\NullTransformationFormatter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '-',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'requiredValidator' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Validators\\RequiredValidator',
    'external' => false,
    'weak' => false,
  ),
  'richTextFieldRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Renderers\\RichTextFieldRenderer',
    'external' => false,
    'weak' => false,
  ),
  'roleDao' => 
  array (
    'class' => 'Test\\Dao\\RoleDao',
    'external' => false,
    'setterBinds' => 
    array (
      'setTdbmService' => 'tdbmService',
    ),
  ),
  'rootController' => 
  array (
    'class' => 'Test\\Controllers\\RootController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'bootstrapTemplate',
      'content' => 'block.content',
    ),
  ),
  'rootUrlInlineWebLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\InlineWebLibrary',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'jsElement' => 'rootUrlJsFile',
    ),
  ),
  'rootUrlJsFile' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlFromFile',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.utils.weblibrarymanager/javascript/rootUrl.php',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'scriptManager' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\ScriptManagers\\ScriptManager',
    'external' => false,
    'weak' => false,
  ),
  'selectFieldRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Renderers\\SelectFieldRenderer',
    'external' => false,
    'weak' => false,
  ),
  'selectFieldRendererradioMode' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Renderers\\SelectFieldRenderer',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'radioMode' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'sessionManager' => 
  array (
    'class' => 'Mouf\\Utils\\Session\\SessionManager\\DefaultSessionManager',
    'external' => false,
  ),
  'skillDao' => 
  array (
    'class' => 'Test\\Dao\\SkillDao',
    'external' => false,
    'setterBinds' => 
    array (
      'setTdbmService' => 'tdbmService',
    ),
  ),
  'splash' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Splash',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'debugMode' => 
      array (
        'value' => 'DEBUG_MODE',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'http404Handler' => 'httpErrorsController',
      'http500Handler' => 'httpErrorsController',
      'cacheService' => 'splashCacheApc',
    ),
  ),
  'splashBrowserLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\BrowserLanguageDetection',
    'external' => false,
    'weak' => false,
  ),
  'splashCacheApc' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\ApcCache',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'fallback' => 'splashCacheFile',
    ),
    'fieldProperties' => 
    array (
      'prefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splashCacheFile' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\FileCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'cacheDirectory' => 
      array (
        'value' => 'splashCache/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'prefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splashTranslateService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'vendor/mouf/mvc.splash-common/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'splashBrowserLanguageDetection',
    ),
  ),
  'subFormFieldWrapperRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\FormRenderers\\Bootstrap\\Wrappers\\SubFormFieldWrapperRenderer',
    'external' => false,
    'weak' => false,
  ),
  'tdbmService' => 
  array (
    'class' => 'Mouf\\Database\\TDBM\\TDBMService',
    'external' => false,
    'setterBinds' => 
    array (
      'setConnection' => 'dbConnection',
      'setCacheService' => 'noCacheService',
    ),
    'setterProperties' => 
    array (
      'setDefaultAutoSaveMode' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'textAreaFieldRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Renderers\\TextAreaFieldRenderer',
    'external' => false,
    'weak' => false,
  ),
  'textFieldRenderer' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Renderers\\TextFieldRenderer',
    'external' => false,
    'weak' => false,
  ),
  'timestampToDateFormatter' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Formatters\\DateFormatter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'timestamp',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'm/d/Y',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'twigEnvironment' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\Twig\\MoufTwigEnvironment',
    'external' => false,
    'weak' => false,
  ),
  'uRLValidatorFtpHttps' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Validators\\URLValidator',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'allowFtp' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'allowHttps' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'userController' => 
  array (
    'class' => 'Test\\Controllers\\UserController',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
    ),
    'fieldBinds' => 
    array (
      'template' => 'bootstrapTemplate',
      'content' => 'block.content',
      'formInstance' => '__anonymous__743966_1390581890217',
    ),
  ),
  'userDao' => 
  array (
    'class' => 'Test\\Dao\\UserDao',
    'external' => false,
    'setterBinds' => 
    array (
      'setTdbmService' => 'tdbmService',
    ),
  ),
  'userForm' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\BCEForm',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'mainDAO' => 'userDao',
      'scriptManager' => 'scriptManager',
      'idFieldDescriptor' => 'userFormidDesc',
      'fieldDescriptors' => 
      array (
        0 => 'userFormroleIdDesc',
        1 => 'userFormnameDesc',
        2 => 'userFormemailDesc',
        3 => 'userFormbirthDateDesc',
        4 => 'userFormstoryDesc',
        5 => 'userSkillsDescriptor',
        6 => 'userProjectsDecriptor',
      ),
      'validationHandler' => 'queryValidateHandler',
      'renderer' => 'aseRenderer',
    ),
    'fieldProperties' => 
    array (
      'action' => 
      array (
        'value' => 'saveUser',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'method' => 
      array (
        'value' => 'POST',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'saveLabel' => 
      array (
        'value' => 'Save changes',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'cancelLabel' => 
      array (
        'value' => 'Cancel',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'attributes' => 
      array (
        'value' => 
        array (
          'name' => 'default_name',
          'id' => 'default_id',
          'acceptCharset' => 'UTF-8',
          'enctype' => 'application/x-www-form-urlencoded',
          'class' => '',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'userFormbirthDateDesc' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Descriptors\\BaseFieldDescriptor',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'fieldWrapperRenderer' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'fieldName' => 
      array (
        'value' => 'birth_date',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'viewCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'getter' => 
      array (
        'value' => 'getBirthDate',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setter' => 
      array (
        'value' => 'setBirthDate',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Birth date',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setDescription' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setValidators' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'formatter' => 'timestampToDateFormatter',
      'renderer' => 'datePickerRenderer',
      'editCondition' => 'falseCondition',
    ),
  ),
  'userFormemailDesc' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Descriptors\\BaseFieldDescriptor',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'fieldName' => 
      array (
        'value' => 'email',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'formatter' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'editCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'viewCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'getter' => 
      array (
        'value' => 'getEmail',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setter' => 
      array (
        'value' => 'setEmail',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Email',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setDescription' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'fieldWrapperRenderer' => 'defaultFieldWrapperRenderer',
      'renderer' => 'textFieldRenderer',
    ),
    'setterBinds' => 
    array (
      'setValidators' => 
      array (
        0 => 'emailValidator',
      ),
    ),
  ),
  'userFormidDesc' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Descriptors\\BaseFieldDescriptor',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'fieldName' => 
      array (
        'value' => 'id',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'formatter' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'getter' => 
      array (
        'value' => 'getId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setter' => 
      array (
        'value' => 'setId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Id',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setDescription' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'fieldWrapperRenderer' => 'noWrapFieldWrapperRenderer',
      'renderer' => 'hiddenRenderer',
    ),
    'setterBinds' => 
    array (
      'setValidators' => 
      array (
        0 => 'numericValidatorDecimals',
      ),
    ),
  ),
  'userFormnameDesc' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Descriptors\\BaseFieldDescriptor',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'fieldName' => 
      array (
        'value' => 'name',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'formatter' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'editCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'viewCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'getter' => 
      array (
        'value' => 'getName',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setter' => 
      array (
        'value' => 'setName',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Name',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setDescription' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'fieldWrapperRenderer' => 'defaultFieldWrapperRenderer',
      'renderer' => 'textFieldRenderer',
    ),
    'setterBinds' => 
    array (
      'setValidators' => 
      array (
        0 => 'requiredValidator',
      ),
    ),
  ),
  'userFormroleIdDesc' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Descriptors\\ForeignKeyFieldDescriptor',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'fieldName' => 
      array (
        'value' => 'role_id',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'formatter' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'editCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'viewCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'getter' => 
      array (
        'value' => 'getRoleId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setter' => 
      array (
        'value' => 'setRoleId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'dataMethod' => 
      array (
        'value' => 'getList',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'linkedIdGetter' => 
      array (
        'value' => 'getId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'linkedLabelGetter' => 
      array (
        'value' => 'getLabel',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Role',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setDescription' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'fieldWrapperRenderer' => 'defaultFieldWrapperRenderer',
      'renderer' => 'selectFieldRenderer',
      'dao' => 'roleDao',
    ),
    'setterBinds' => 
    array (
      'setValidators' => 
      array (
        0 => 'numericValidatorDecimals',
      ),
    ),
  ),
  'userFormstoryDesc' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Descriptors\\BaseFieldDescriptor',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'fieldName' => 
      array (
        'value' => 'story',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'formatter' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'editCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'viewCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'getter' => 
      array (
        'value' => 'getStory',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setter' => 
      array (
        'value' => 'setStory',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Story',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setDescription' => 
      array (
        'value' => 'Tell us some interesting facts about you !',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setValidators' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'fieldWrapperRenderer' => 'defaultFieldWrapperRenderer',
      'renderer' => 'textAreaFieldRenderer',
    ),
  ),
  'userMessageService' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\MessageService\\Service\\SessionMessageService',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'sessionManager' => 'sessionManager',
    ),
  ),
  'userProjectsDecriptor' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Descriptors\\SubFormFieldDescriptor',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'fieldName' => 
      array (
        'value' => 'user_projects',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'fieldLabel' => 
      array (
        'value' => 'Projects',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'description' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'beansGetter' => 
      array (
        'value' => 'getByUserBean',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'fkGetter' => 
      array (
        'value' => 'getUserId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'fkSetter' => 
      array (
        'value' => 'setUserId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'itemWrapperRenderer' => 'bootstrapSubFormItemWrapper',
      'form' => 'projectForm',
    ),
  ),
  'userSkillDao' => 
  array (
    'class' => 'Test\\Dao\\UserSkillDao',
    'external' => false,
    'setterBinds' => 
    array (
      'setTdbmService' => 'tdbmService',
    ),
  ),
  'userSkillsDescriptor' => 
  array (
    'class' => 'Mouf\\MVC\\BCE\\Classes\\Descriptors\\Many2ManyFieldDescriptor',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'fieldName' => 
      array (
        'value' => 'user_skills',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'formatter' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'editCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'viewCondition' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'mappingIdGetter' => 
      array (
        'value' => 'getId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'mappingLeftKeySetter' => 
      array (
        'value' => 'setUserId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'mappingRightKeyGetter' => 
      array (
        'value' => 'getSkillId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'mappingRightKeySetter' => 
      array (
        'value' => 'setSkillId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'beanValuesMethod' => 
      array (
        'value' => 'getByUserId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'linkedIdGetter' => 
      array (
        'value' => 'getId',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'linkedLabelGetter' => 
      array (
        'value' => 'getLabel',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'dataMethod' => 
      array (
        'value' => 'getList',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Skills',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setDescription' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setValidators' => 
      array (
        'value' => NULL,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'fieldWrapperRenderer' => 'defaultFieldWrapperRenderer',
      'renderer' => 'multipleSelectFieldRenderer2',
      'mappingDao' => 'userSkillDao',
      'linkedDao' => 'skillDao',
    ),
  ),
  'validatorsBrowserLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\BrowserLanguageDetection',
    'external' => false,
  ),
  'validatorsTranslateService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'vendor/mouf/utils.common.validators/src/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'validatorsBrowserLanguageDetection',
    ),
  ),
));


unset($moufManager);

/**
				* This is the base class of the Manage Object User Friendly or Modular object user framework (MOUF) framework.
				* This object can be used to get the objects manage by MOUF.
				*
				*/
				class Mouf {
					/**
	 * @return Mouf\Utils\Cache\ApcCache
	 */
	 public static function getApcCacheService() {
	 	return MoufManager::getMoufManager()->getInstance('apcCacheService');
	 }

	/**
	 * @return Mouf\MVC\BCE\FormRenderers\Bootstrap\BootstrapFormRenderer
	 */
	 public static function getAseRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('aseRenderer');
	 }

	/**
	 * @return Mouf\MVC\BCE\Services\BCEUtils
	 */
	 public static function getBceUtils() {
	 	return MoufManager::getMoufManager()->getInstance('bceUtils');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_content() {
	 	return MoufManager::getMoufManager()->getInstance('block.content');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_footer() {
	 	return MoufManager::getMoufManager()->getInstance('block.footer');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_header() {
	 	return MoufManager::getMoufManager()->getInstance('block.header');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_left() {
	 	return MoufManager::getMoufManager()->getInstance('block.left');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_right() {
	 	return MoufManager::getMoufManager()->getInstance('block.right');
	 }

	/**
	 * @return Mouf\MVC\BCE\FormRenderers\Bootstrap\Wrappers\DescriptionRenderer\BlockDescriptionRenderer
	 */
	 public static function getBlockDescriptionRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('blockDescriptionRenderer');
	 }

	/**
	 * @return Mouf\Utils\Common\Formatters\PrefixSuffixFormatter
	 */
	 public static function getBoldFormatter() {
	 	return MoufManager::getMoufManager()->getInstance('boldFormatter');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Renderers\BooleanFieldRenderer
	 */
	 public static function getBooleanFieldRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('booleanFieldRenderer');
	 }

	/**
	 * @return Mouf\MVC\BCE\FormRenderers\Bootstrap\BootstrapFormRenderer
	 */
	 public static function getBootstrapFormRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('bootstrapFormRenderer');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getBootstrapRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('bootstrapRenderer');
	 }

	/**
	 * @return Mouf\MVC\BCE\FormRenderers\Bootstrap\Wrappers\BootstrapSubFormItemWrapper
	 */
	 public static function getBootstrapSubFormItemWrapper() {
	 	return MoufManager::getMoufManager()->getInstance('bootstrapSubFormItemWrapper');
	 }

	/**
	 * @return Mouf\Html\Template\BootstrapTemplate
	 */
	 public static function getBootstrapTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('bootstrapTemplate');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Renderers\ColorPickerRenderer
	 */
	 public static function getColorPickerRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('colorPickerRenderer');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getCustomRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('customRenderer');
	 }

	/**
	 * @return Test\Dao\DaoFactory
	 */
	 public static function getDaoFactory() {
	 	return MoufManager::getMoufManager()->getInstance('daoFactory');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Renderers\DatePickerRenderer
	 */
	 public static function getDatePickerRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('datePickerRenderer');
	 }

	/**
	 * @return Mouf\Database\DBConnection\MySqlConnection
	 */
	 public static function getDbConnection() {
	 	return MoufManager::getMoufManager()->getInstance('dbConnection');
	 }

	/**
	 * @return Mouf\MVC\BCE\FormRenderers\Bootstrap\Wrappers\DefaultFieldWrapperRenderer
	 */
	 public static function getDefaultFieldWrapperRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('defaultFieldWrapperRenderer');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Language\BrowserLanguageDetection
	 */
	 public static function getDefaultLanguageDetection() {
	 	return MoufManager::getMoufManager()->getInstance('defaultLanguageDetection');
	 }

	/**
	 * @return Mouf\Html\Renderer\AutoChainRenderer
	 */
	 public static function getDefaultRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('defaultRenderer');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getDefaultTranslationService() {
	 	return MoufManager::getMoufManager()->getInstance('defaultTranslationService');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibraryManager
	 */
	 public static function getDefaultWebLibraryManager() {
	 	return MoufManager::getMoufManager()->getInstance('defaultWebLibraryManager');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\DefaultWebLibraryRenderer
	 */
	 public static function getDefaultWebLibraryRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('defaultWebLibraryRenderer');
	 }

	/**
	 * @return Mouf\Utils\Common\Validators\EmailValidator
	 */
	 public static function getEmailValidator() {
	 	return MoufManager::getMoufManager()->getInstance('emailValidator');
	 }

	/**
	 * @return Mouf\Utils\Log\ErrorLogLogger
	 */
	 public static function getErrorLogLogger() {
	 	return MoufManager::getMoufManager()->getInstance('errorLogLogger');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getEvolugridLibrary() {
	 	return MoufManager::getMoufManager()->getInstance('evolugridLibrary');
	 }

	/**
	 * @return Mouf\Utils\Common\ConditionInterface\FalseCondition
	 */
	 public static function getFalseCondition() {
	 	return MoufManager::getMoufManager()->getInstance('falseCondition');
	 }

	/**
	 * @return Mouf\Utils\Cache\FileCache
	 */
	 public static function getFileCacheService() {
	 	return MoufManager::getMoufManager()->getInstance('fileCacheService');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getFileUploaderLibrary() {
	 	return MoufManager::getMoufManager()->getInstance('fileUploaderLibrary');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Renderers\FileUploaderRenderer
	 */
	 public static function getFileUploaderRendererNoonlyOneFile() {
	 	return MoufManager::getMoufManager()->getInstance('fileUploaderRendererNoonlyOneFile');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Renderers\FileUploaderRenderer
	 */
	 public static function getFileUploaderRendereronlyOneFile() {
	 	return MoufManager::getMoufManager()->getInstance('fileUploaderRendereronlyOneFile');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getFineCommonTranslationService() {
	 	return MoufManager::getMoufManager()->getInstance('fineCommonTranslationService');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Renderers\HiddenRenderer
	 */
	 public static function getHiddenRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('hiddenRenderer');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Controllers\HttpErrorsController
	 */
	 public static function getHttpErrorsController() {
	 	return MoufManager::getMoufManager()->getInstance('httpErrorsController');
	 }

	/**
	 * @return Mouf\Utils\Common\Formatters\PrefixSuffixFormatter
	 */
	 public static function getItalicFormatter() {
	 	return MoufManager::getMoufManager()->getInstance('italicFormatter');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJQueryHistory() {
	 	return MoufManager::getMoufManager()->getInstance('jQueryHistory');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJQueryLibrary() {
	 	return MoufManager::getMoufManager()->getInstance('jQueryLibrary');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJQueryUiLibrary() {
	 	return MoufManager::getMoufManager()->getInstance('jQueryUiLibrary');
	 }

	/**
	 * @return Mouf\Html\Utils\I18nWebLibrary\I18nWebLibrary
	 */
	 public static function getJQueryValidateLibrary() {
	 	return MoufManager::getMoufManager()->getInstance('jQueryValidateLibrary');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_bootstrap() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.bootstrap');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_ckeditor() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.ckeditor');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getMessageServiceLibrary() {
	 	return MoufManager::getMoufManager()->getInstance('messageServiceLibrary');
	 }

	/**
	 * @return Mouf\Html\Widgets\MessageService\Widget\MessageWidget
	 */
	 public static function getMessageWidget() {
	 	return MoufManager::getMoufManager()->getInstance('messageWidget');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Renderers\MultipleSelectFieldRenderer
	 */
	 public static function getMultipleSelectFieldRenderer2() {
	 	return MoufManager::getMoufManager()->getInstance('multipleSelectFieldRenderer2');
	 }

	/**
	 * @return Mouf\Utils\Cache\NoCache
	 */
	 public static function getNoCacheService() {
	 	return MoufManager::getMoufManager()->getInstance('noCacheService');
	 }

	/**
	 * @return Mouf\MVC\BCE\FormRenderers\NoWrapFieldWrapperRenderer
	 */
	 public static function getNoWrapFieldWrapperRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('noWrapFieldWrapperRenderer');
	 }

	/**
	 * @return Mouf\Utils\Common\Validators\NumericValidator
	 */
	 public static function getNumericValidatorDecimals() {
	 	return MoufManager::getMoufManager()->getInstance('numericValidatorDecimals');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufhtml_widgets_formelements() {
	 	return MoufManager::getMoufManager()->getInstance('packageRenderer_mouf/html.widgets.form-elements');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufhtml_widgets_messageservice() {
	 	return MoufManager::getMoufManager()->getInstance('packageRenderer_mouf/html.widgets.messageservice');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Renderers\PasswordFieldRenderer
	 */
	 public static function getPasswordFieldRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('passwordFieldRenderer');
	 }

	/**
	 * @return Test\Dao\ProjectDao
	 */
	 public static function getProjectDao() {
	 	return MoufManager::getMoufManager()->getInstance('projectDao');
	 }

	/**
	 * @return Mouf\MVC\BCE\BCEForm
	 */
	 public static function getProjectForm() {
	 	return MoufManager::getMoufManager()->getInstance('projectForm');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Descriptors\BaseFieldDescriptor
	 */
	 public static function getProjectFormidDesc() {
	 	return MoufManager::getMoufManager()->getInstance('projectFormidDesc');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Descriptors\BaseFieldDescriptor
	 */
	 public static function getProjectFormlabelDesc() {
	 	return MoufManager::getMoufManager()->getInstance('projectFormlabelDesc');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Descriptors\ForeignKeyFieldDescriptor
	 */
	 public static function getProjectFormuserIdDesc() {
	 	return MoufManager::getMoufManager()->getInstance('projectFormuserIdDesc');
	 }

	/**
	 * @return Mouf\Utils\Log\Psr\ErrorLogLogger
	 */
	 public static function getPsr_errorLogLogger() {
	 	return MoufManager::getMoufManager()->getInstance('psr.errorLogLogger');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\ValidationHandlers\JQueryValidateHandler
	 */
	 public static function getQueryValidateHandler() {
	 	return MoufManager::getMoufManager()->getInstance('queryValidateHandler');
	 }

	/**
	 * @return Mouf\Utils\Common\Formatters\ReadOnlyCheckboxFormatter
	 */
	 public static function getReadOnlyCheckBoxFormatter() {
	 	return MoufManager::getMoufManager()->getInstance('readOnlyCheckBoxFormatter');
	 }

	/**
	 * @return Mouf\Utils\Cache\InMemoryCache
	 */
	 public static function getRendererCacheService() {
	 	return MoufManager::getMoufManager()->getInstance('rendererCacheService');
	 }

	/**
	 * @return Mouf\Utils\Common\Formatters\NullTransformationFormatter
	 */
	 public static function getReplaceNullWithHyphen() {
	 	return MoufManager::getMoufManager()->getInstance('replaceNullWithHyphen');
	 }

	/**
	 * @return Mouf\Utils\Common\Validators\RequiredValidator
	 */
	 public static function getRequiredValidator() {
	 	return MoufManager::getMoufManager()->getInstance('requiredValidator');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Renderers\RichTextFieldRenderer
	 */
	 public static function getRichTextFieldRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('richTextFieldRenderer');
	 }

	/**
	 * @return Test\Dao\RoleDao
	 */
	 public static function getRoleDao() {
	 	return MoufManager::getMoufManager()->getInstance('roleDao');
	 }

	/**
	 * @return Test\Controllers\RootController
	 */
	 public static function getRootController() {
	 	return MoufManager::getMoufManager()->getInstance('rootController');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\InlineWebLibrary
	 */
	 public static function getRootUrlInlineWebLibrary() {
	 	return MoufManager::getMoufManager()->getInstance('rootUrlInlineWebLibrary');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlFromFile
	 */
	 public static function getRootUrlJsFile() {
	 	return MoufManager::getMoufManager()->getInstance('rootUrlJsFile');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\ScriptManagers\ScriptManager
	 */
	 public static function getScriptManager() {
	 	return MoufManager::getMoufManager()->getInstance('scriptManager');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Renderers\SelectFieldRenderer
	 */
	 public static function getSelectFieldRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('selectFieldRenderer');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Renderers\SelectFieldRenderer
	 */
	 public static function getSelectFieldRendererradioMode() {
	 	return MoufManager::getMoufManager()->getInstance('selectFieldRendererradioMode');
	 }

	/**
	 * @return Mouf\Utils\Session\SessionManager\DefaultSessionManager
	 */
	 public static function getSessionManager() {
	 	return MoufManager::getMoufManager()->getInstance('sessionManager');
	 }

	/**
	 * @return Test\Dao\SkillDao
	 */
	 public static function getSkillDao() {
	 	return MoufManager::getMoufManager()->getInstance('skillDao');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Splash
	 */
	 public static function getSplash() {
	 	return MoufManager::getMoufManager()->getInstance('splash');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Language\BrowserLanguageDetection
	 */
	 public static function getSplashBrowserLanguageDetection() {
	 	return MoufManager::getMoufManager()->getInstance('splashBrowserLanguageDetection');
	 }

	/**
	 * @return Mouf\Utils\Cache\ApcCache
	 */
	 public static function getSplashCacheApc() {
	 	return MoufManager::getMoufManager()->getInstance('splashCacheApc');
	 }

	/**
	 * @return Mouf\Utils\Cache\FileCache
	 */
	 public static function getSplashCacheFile() {
	 	return MoufManager::getMoufManager()->getInstance('splashCacheFile');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getSplashTranslateService() {
	 	return MoufManager::getMoufManager()->getInstance('splashTranslateService');
	 }

	/**
	 * @return Mouf\MVC\BCE\FormRenderers\Bootstrap\Wrappers\SubFormFieldWrapperRenderer
	 */
	 public static function getSubFormFieldWrapperRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('subFormFieldWrapperRenderer');
	 }

	/**
	 * @return Mouf\Database\TDBM\TDBMService
	 */
	 public static function getTdbmService() {
	 	return MoufManager::getMoufManager()->getInstance('tdbmService');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Renderers\TextAreaFieldRenderer
	 */
	 public static function getTextAreaFieldRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('textAreaFieldRenderer');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Renderers\TextFieldRenderer
	 */
	 public static function getTextFieldRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('textFieldRenderer');
	 }

	/**
	 * @return Mouf\Utils\Common\Formatters\DateFormatter
	 */
	 public static function getTimestampToDateFormatter() {
	 	return MoufManager::getMoufManager()->getInstance('timestampToDateFormatter');
	 }

	/**
	 * @return Mouf\Html\Renderer\Twig\MoufTwigEnvironment
	 */
	 public static function getTwigEnvironment() {
	 	return MoufManager::getMoufManager()->getInstance('twigEnvironment');
	 }

	/**
	 * @return Mouf\Utils\Common\Validators\URLValidator
	 */
	 public static function getURLValidatorFtpHttps() {
	 	return MoufManager::getMoufManager()->getInstance('uRLValidatorFtpHttps');
	 }

	/**
	 * @return Test\Controllers\UserController
	 */
	 public static function getUserController() {
	 	return MoufManager::getMoufManager()->getInstance('userController');
	 }

	/**
	 * @return Test\Dao\UserDao
	 */
	 public static function getUserDao() {
	 	return MoufManager::getMoufManager()->getInstance('userDao');
	 }

	/**
	 * @return Mouf\MVC\BCE\BCEForm
	 */
	 public static function getUserForm() {
	 	return MoufManager::getMoufManager()->getInstance('userForm');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Descriptors\BaseFieldDescriptor
	 */
	 public static function getUserFormbirthDateDesc() {
	 	return MoufManager::getMoufManager()->getInstance('userFormbirthDateDesc');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Descriptors\BaseFieldDescriptor
	 */
	 public static function getUserFormemailDesc() {
	 	return MoufManager::getMoufManager()->getInstance('userFormemailDesc');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Descriptors\BaseFieldDescriptor
	 */
	 public static function getUserFormidDesc() {
	 	return MoufManager::getMoufManager()->getInstance('userFormidDesc');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Descriptors\BaseFieldDescriptor
	 */
	 public static function getUserFormnameDesc() {
	 	return MoufManager::getMoufManager()->getInstance('userFormnameDesc');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Descriptors\ForeignKeyFieldDescriptor
	 */
	 public static function getUserFormroleIdDesc() {
	 	return MoufManager::getMoufManager()->getInstance('userFormroleIdDesc');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Descriptors\BaseFieldDescriptor
	 */
	 public static function getUserFormstoryDesc() {
	 	return MoufManager::getMoufManager()->getInstance('userFormstoryDesc');
	 }

	/**
	 * @return Mouf\Html\Widgets\MessageService\Service\SessionMessageService
	 */
	 public static function getUserMessageService() {
	 	return MoufManager::getMoufManager()->getInstance('userMessageService');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Descriptors\SubFormFieldDescriptor
	 */
	 public static function getUserProjectsDecriptor() {
	 	return MoufManager::getMoufManager()->getInstance('userProjectsDecriptor');
	 }

	/**
	 * @return Test\Dao\UserSkillDao
	 */
	 public static function getUserSkillDao() {
	 	return MoufManager::getMoufManager()->getInstance('userSkillDao');
	 }

	/**
	 * @return Mouf\MVC\BCE\Classes\Descriptors\Many2ManyFieldDescriptor
	 */
	 public static function getUserSkillsDescriptor() {
	 	return MoufManager::getMoufManager()->getInstance('userSkillsDescriptor');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Language\BrowserLanguageDetection
	 */
	 public static function getValidatorsBrowserLanguageDetection() {
	 	return MoufManager::getMoufManager()->getInstance('validatorsBrowserLanguageDetection');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getValidatorsTranslateService() {
	 	return MoufManager::getMoufManager()->getInstance('validatorsTranslateService');
	 }

}
?>
